# Generated by Django 3.0.4 on 2020-03-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('hint', models.TextField(default='')),
                ('special_letter', models.CharField(max_length=5)),
                ('etc', models.TextField(default='')),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=64)),
                ('ptail', models.CharField(max_length=64)),
                ('site_id', models.CharField(max_length=64)),
                ('etc', models.TextField(default='')),
                ('status', models.CharField(max_length=20)),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('pheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.PasswordHeader')),
            ],
        ),
    ]
