# Generated by Django 3.0.4 on 2020-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='etc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='passwordheader',
            name='etc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='passwordheader',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
