# Generated by Django 3.2.6 on 2021-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='etc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='site_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='password',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordheader',
            name='etc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='passwordheader',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
