# Generated by Django 3.0.4 on 2020-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_auto_20200321_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='site_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='password',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
