# Generated by Django 3.0.4 on 2020-03-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_testheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestHeader',
        ),
    ]
