# Generated by Django 3.2.6 on 2021-12-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128)),
                ('contents', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('READ', 'Read'), ('NOT_READ', 'not read')], default='NOT_READ', max_length=20)),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
