# Generated by Django 3.2.6 on 2021-12-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarycontents',
            old_name='contents',
            new_name='text',
        ),
    ]
