# Generated by Django 3.2.6 on 2021-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diarycontents_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarycontents',
            name='date',
        ),
        migrations.AddField(
            model_name='diarycontents',
            name='date_title',
            field=models.TextField(default=None),
        ),
    ]
