# Generated by Django 3.2.6 on 2021-12-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20211229_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycontents',
            name='date_title',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
