# Generated by Django 3.2.6 on 2022-05-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordscontents',
            old_name='name',
            new_name='word',
        ),
    ]
