# Generated by Django 3.2.6 on 2021-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JcsgContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=None, max_length=20)),
                ('title', models.CharField(default=None, max_length=128)),
                ('contents', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
