# Generated by Django 3.2.6 on 2021-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jcsgcontents',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
