# Generated by Django 3.0.4 on 2020-11-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrvLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
