# Generated by Django 3.0.4 on 2020-11-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_bp', models.IntegerField(blank=True, default=None)),
                ('dia_bp', models.IntegerField(blank=True, default=None)),
                ('pulse', models.IntegerField(blank=True, default=None)),
                ('weight', models.FloatField(blank=True, default=None)),
                ('param', models.TextField(blank=True, default=None)),
                ('type', models.CharField(default=None, max_length=20)),
                ('status', models.CharField(default=None, max_length=20)),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
