# Generated by Django 3.0.4 on 2020-11-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('search_form', models.CharField(max_length=256)),
                ('list_webtoon', models.TextField()),
                ('contents_webtoon', models.TextField()),
                ('main_url', models.CharField(max_length=256)),
                ('etc', models.TextField()),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prt_uid', models.TextField()),
                ('title', models.CharField(max_length=64)),
                ('today_title', models.TextField()),
                ('wid', models.CharField(max_length=32)),
                ('lastno', models.CharField(max_length=32)),
                ('dates', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=20)),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.Portal')),
            ],
        ),
    ]
