# Generated by Django 3.0.4 on 2021-06-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webtoon',
            name='prt_uid',
        ),
    ]
